import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CheckCircle2, ChevronLeft, ChevronRight, Package, Repeat, Truck, X, LogOut } from 'lucide-react';
import { Fault, Operator, SystemConfig } from '../../types';
import { soundEffects } from '../../services/soundEffects';

interface Props {
  isOpen: boolean; onClose: () => void; fault: Fault | null; currentOperator: Operator; config: SystemConfig;
  onSubmitClose: (p:{actionTaken:string;partsChanged:string;faultReason:string;stoppageReason:string;operatorName:string;minutes:number;helperMinutes?:Record<string,number>})=>Promise<void>;
  onSubmitStatusUpdate:(status:Fault['status'],note?:string,minutes?:number)=>Promise<void>;
}
const labels=['Sonuç','Nedenler','Yapılan İş','Parça','Özet'];
export const InterventionModal:React.FC<Props>=({isOpen,onClose,fault,currentOperator,config,onSubmitClose,onSubmitStatusUpdate})=>{
 const [step,setStep]=useState(1),[status,setStatus]=useState<Fault['status']>('Kapalı'),[action,setAction]=useState(''),[part,setPart]=useState(''),[faultReason,setFaultReason]=useState(''),[stopReason,setStopReason]=useState(''),[minutes,setMinutes]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(isOpen&&fault){setStep(1);setStatus('Kapalı');setAction(fault.actionTaken||'');setPart(fault.partsChanged==='-'?'':fault.partsChanged||'');setFaultReason(fault.faultReason||config.faultReasons?.[0]||'');setStopReason(fault.stoppageReason||config.stoppageReasons?.[0]||'');const t=fault.startedAt||fault.createdAt;setMinutes(t?Math.max(1,Math.round((Date.now()-new Date(t).getTime())/60000)):1);setError('')}},[isOpen,fault,config]);
 const fr=useMemo(()=>Array.from(new Set([fault?.faultReason,...(config.faultReasons||[])].filter(Boolean))) as string[],[fault,config]);
 const sr=useMemo(()=>Array.from(new Set([fault?.stoppageReason,...(config.stoppageReasons||[])].filter(Boolean))) as string[],[fault,config]);
 if(!isOpen||!fault)return null; const closed=status==='Kapalı';
 const options:Array<[Fault['status'],string,string,React.ElementType]>=[['Kapalı','Arızayı Kapat','Arıza çözüldü ve makine hazır',CheckCircle2],['Parça Bekliyor','Yedek Parça Bekliyor','Parça temini sonrası devam',Package],['Devredildi','Vardiyaya Devredildi','Sonraki vardiya devam edecek',Repeat],['Açık','Açık Bırak','Arıza açık kalsın',LogOut],['Dış Servis Bekliyor','Dış Servis Bekliyor','Servis müdahalesi gerekli',Truck]];
 const valid=()=>{setError('');if(step===2&&closed&&(!faultReason||!stopReason)){setError('Arıza ve duruş nedeni seçilmelidir.');return false}if(step===3&&closed&&!action.trim()){setError('Yapılan işlem yazılmalıdır.');return false}return true};
 const submit=async()=>{if(busy||!valid())return;setBusy(true);try{if(closed){await onSubmitClose({actionTaken:action.trim(),partsChanged:part.trim(),faultReason,stoppageReason:stopReason,operatorName:currentOperator.name,minutes:Number(minutes)||1});soundEffects.playCompleteFanfare()}else{await onSubmitStatusUpdate(status,action.trim(),Number(minutes)||1);soundEffects.playSuccessBeep()}onClose()}catch{setError('Kayıt tamamlanamadı. Tekrar deneyin.')}finally{setBusy(false)}};
 const summary=[['Makine',fault.machine],['Sonuç',status],['Arıza Nedeni',closed?faultReason:'Gerekli değil'],['Duruş Nedeni',closed?stopReason:'Gerekli değil'],['Yapılan İş / Not',action||'-'],['Değişen Parça',part||'Yok'],['Süre',`${minutes} dakika`]];
 return <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-sm flex items-center justify-center p-3"><div className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl flex flex-col max-h-[92vh]">
  <div className="p-4 bg-slate-950 border-b border-slate-800 flex justify-between"><div><h3 className="font-bold text-white">🛠️ Arızaya Müdahale</h3><p className="text-xs text-cyan-300 font-bold">{fault.machine}</p></div><button onClick={onClose}><X className="w-5 h-5"/></button></div>
  <div className="px-4 py-3 border-b border-slate-800 flex gap-1">{labels.map((x,i)=><div className="flex-1 text-center" key={x}><div className={`h-1.5 rounded ${step>=i+1?'bg-cyan-500':'bg-slate-700'}`}/><span className={`text-[9px] ${step===i+1?'text-cyan-300':'text-slate-500'}`}>{i+1}. {x}</span></div>)}</div>
  <div className="p-4 overflow-y-auto flex-1 space-y-4 text-sm">{error&&<div className="p-3 bg-rose-950 border border-rose-700 rounded-xl text-rose-300 flex gap-2"><AlertTriangle className="w-4 h-4"/>{error}</div>}
   {step===1&&<div className="space-y-2"><h4 className="font-bold text-cyan-300">1. İşlem sonucunu seçin</h4>{options.map(([id,title,desc,Icon])=><button key={id} onClick={()=>setStatus(id)} className={`w-full p-3 rounded-xl border flex gap-3 text-left ${status===id?'bg-cyan-950 border-cyan-500':'bg-slate-950/50 border-slate-700'}`}><Icon className="w-5 h-5 text-cyan-400"/><div className="flex-1"><b className="text-white block">{title}</b><small className="text-slate-400">{desc}</small></div>{status===id&&<Check className="text-emerald-400"/>}</button>)}</div>}
   {step===2&&<div className="space-y-4"><h4 className="font-bold text-cyan-300">2. Arıza ve duruş nedenleri</h4>{!closed&&<p className="p-3 bg-amber-950/40 rounded-xl text-amber-300">Bu durumda neden seçimi zorunlu değildir.</p>}<label className="block">Arıza Nedeni<select disabled={!closed} value={faultReason} onChange={e=>setFaultReason(e.target.value)} className="mt-1 w-full p-3 bg-slate-950 border border-slate-700 rounded-xl"><option value="">Seçiniz</option>{fr.map(x=><option key={x}>{x}</option>)}</select></label><label className="block">Duruş Nedeni<select disabled={!closed} value={stopReason} onChange={e=>setStopReason(e.target.value)} className="mt-1 w-full p-3 bg-slate-950 border border-slate-700 rounded-xl"><option value="">Seçiniz</option>{sr.map(x=><option key={x}>{x}</option>)}</select></label></div>}
   {step===3&&<div className="space-y-3"><h4 className="font-bold text-cyan-300">3. Yapılan işlemi yazın</h4><textarea rows={7} value={action} onChange={e=>setAction(e.target.value)} className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl" placeholder="Yapılan işlem veya devir notu"/><label className="block">Süre (dakika)<input type="number" min="1" value={minutes} onChange={e=>setMinutes(Math.max(1,Number(e.target.value)))} className="mt-1 w-full p-3 bg-slate-950 border border-slate-700 rounded-xl"/></label></div>}
   {step===4&&<div className="space-y-3"><h4 className="font-bold text-cyan-300">4. Değişen parça</h4><input value={part} onChange={e=>setPart(e.target.value)} className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl" placeholder="Parça yoksa boş bırakın"/><small className="text-slate-400">Örnek: Sensör, kayış, rulman</small></div>}
   {step===5&&<div className="space-y-3"><h4 className="font-bold text-cyan-300">5. Kontrol edin ve kaydedin</h4><div className="divide-y divide-slate-800 border border-slate-700 rounded-xl overflow-hidden">{summary.map(([k,v])=><div key={k} className="grid grid-cols-2 p-3 bg-slate-950/40"><span className="text-slate-400">{k}</span><b className="text-white whitespace-pre-wrap">{v}</b></div>)}</div><p className="text-emerald-300 text-xs">Kayıt başarılı olunca pencere otomatik kapanır.</p></div>}
  </div>
  <div className="p-4 border-t border-slate-800 bg-slate-950 flex gap-2">{step>1&&<button onClick={()=>{setError('');setStep(s=>s-1)}} className="flex-1 p-3 border border-slate-700 rounded-xl flex justify-center gap-2"><ChevronLeft/>Geri</button>}{step<5?<button onClick={()=>valid()&&setStep(s=>s+1)} className="flex-1 p-3 bg-cyan-600 rounded-xl font-bold flex justify-center gap-2">Devam<ChevronRight/></button>:<button onClick={submit} disabled={busy} className="flex-1 p-3 bg-emerald-600 rounded-xl font-bold disabled:opacity-50">{busy?'Kaydediliyor...':'Kaydet ve Güncelle'}</button>}</div>
 </div></div>
}
